---
title: "Repositorios"
---
```{r setup, include = FALSE}
library(DT)
library(comprehenr)
recursos_CB_EC <- tibble(read_excel("./data/Recursos digitales del curso b치sico.xlsx", sheet = "EC", na ="0"))

recursos_CB_HN <- tibble(read_excel("./data/Recursos digitales del curso b치sico.xlsx", sheet = "HN", na ="0"))

recursos_CB_SV <- tibble(read_excel("./data/Recursos digitales del curso b치sico.xlsx", sheet = "SV", na ="0"))


recursos_CB <- bind_rows(recursos_CB_EC, recursos_CB_HN, recursos_CB_SV)
```

```{r, echo = FALSE, message=FALSE, warning=FALSE}
urls <-to_list(for (val in unlist(recursos_CB['Link al recurso'])) 
  if (is.na(val)) 'Pronto colocaremos la URL' else paste("<input type=button value=Nueva ventana onclick=javascript:window.open('http://norfipc.com/','','width=600,height=400,left=50,top=50,toolbar=yes');/>"))


recursos_CB$'Link al recurso'=unlist(urls)

data <- recursos_CB%>% select('Tipo','Nombre del recurso', 'Tema ense침ado con el recurso', 'Link al recurso')
datatable(
  data,filter = "top",
  options = list(dom = 'Pfrtip', columnDefs = list(list(
    searchPanes = list(show = FALSE), targets = 0:-1
  ))),escape = FALSE,
  extensions = c('Select', 'SearchPanes'),
  selection = 'none'
)


``````
