# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R

on:
  schedule:
    - cron: "* * * * *"

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up R 3.5
        uses: r-lib/actions/setup-r@ffe45a39586f073cc2e9af79c4ba563b657dc6e3
        with:
          r-version: '3.5'
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
          file.remove("/data/Recursos digitales del curso básico.xlsx")
          download.file(
            url = "https://docs.google.com/spreadsheets/d/1BVxs8O0QpBNz1mdPGFYgV0bLAv3g22QWDDxdsd1XTC4/edit?usp=sharing", 
            destfile = "/data/Recursos digitales del curso básico.xlsx"
          )
          
         
        
